In [10]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\windows\appdata\local\programs\python\python312\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\windows\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\windows\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\windows\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\windows\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\windows\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
!pip install matplotlib seaborn

Requirement already satisfied: matplotlib in c:\users\windows\appdata\local\programs\python\python312\lib\site-packages (3.10.3)
Requirement already satisfied: seaborn in c:\users\windows\appdata\local\programs\python\python312\lib\site-packages (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\windows\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\windows\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\windows\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (4.58.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\windows\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in c:\users\windows\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (2.2.6)
Requirement already satisfied: packaging>=20.0 in c:\users\windows\appdata\roaming\python\python312\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\windows\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\windows\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\windows\appdata\roaming\python\python312\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in c:\users\windows\appdata\local\programs\python\python312\lib\site-packages (from seaborn) (2.2.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\windows\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\windows\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\windows\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 24.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import matplotlib.pyplot as plt

In [5]:
import seaborn as sns

In [14]:


# Load dataset
df = pd.read_csv("C:/Users/WINDOWS/Downloads/agriculture_data.csv")

print(df.columns.tolist())

# Clean column names
df.columns = df.columns.str.strip()

# Print column names to identify correct labels
print("Column Names:")
print(df.columns.tolist())

# Display head
print("\nData Preview:")
display(df.head())

# Info and statistics
print("\nDataset Info:")
df.info()
print("\nSummary Statistics:")
display(df.describe())

# OPTIONAL: Try to auto-detect correct column names (manually adjust if needed)
# Try to find columns similar to 'Rainfall' and 'Crop Yield'
rainfall_col = [col for col in df.columns if 'rain' in col.lower()][0]
yield_col = [col for col in df.columns if 'yield' in col.lower()][0]
crop_col = [col for col in df.columns if 'crop' in col.lower()][0]

print(f"\nUsing columns: Rainfall = {rainfall_col}, Yield = {yield_col}, Crop = {crop_col}")

# Plot
plt.figure(figsize=(8, 5))
sns.scatterplot(data=df, x=rainfall_col, y=yield_col, hue=crop_col)
plt.title('Crop Yield vs Rainfall')
plt.xlabel(rainfall_col)
plt.ylabel(yield_col)
plt.grid(True)
plt.tight_layout()
plt.show()

['State', 'Crop', 'Year', 'Area_Hectares', 'Production_Tonnes']
Column Names:
['State', 'Crop', 'Year', 'Area_Hectares', 'Production_Tonnes']

Data Preview:

         State       Crop  Year  Area_Hectares  Production_Tonnes
0   Tamil Nadu       Rice  2020        1200000            3600000
1       Kerala     Banana  2020         450000            1600000
2       Punjab      Wheat  2020        1800000            5400000
3      Gujarat     Cotton  2020         700000            1800000
4  Maharashtra  Sugarcane  2020         900000            7200000

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State              5 non-null      object
 1   Crop               5 non-null      object
 2   Year               5 non-null      int64
 3   Area_Hectares      5 non-null      int64
 4   Production_Tonnes  5 non-null      int64
dtypes: int64(3), object(2)
memory usage: 332.0+ bytes

Summary Statistics:

         Year  Area_Hectares  Production_Tonnes
count     5.0   5.000000e+00       5.000000e+00
mean   2020.0   1.010000e+06       3.920000e+06
std       0.0   5.200961e+05       2.394160e+06
min    2020.0   4.500000e+05       1.600000e+06
25%    2020.0   7.000000e+05       1.800000e+06
50%    2020.0   9.000000e+05       3.600000e+06
75%    2020.0   1.200000e+06       5.400000e+06
max    2020.0   1.800000e+06       7.200000e+06

IndexError: list index out of range

In [15]:

df = pd.read_csv("C:/Users/WINDOWS/Downloads/agriculture_data.csv")

# Step 2: Clean column names (remove leading/trailing spaces)
df.columns = df.columns.str.strip()

# Step 3: Print all column names
print("\n🧾 Column Names in Your Dataset:")
print(df.columns.tolist())

# Step 4: Preview data
print("\n📊 Data Preview:")
print(df.head())

# Step 5: Info & Stats
print("\n🔍 Dataset Info:")
df.info()

print("\n📈 Summary Statistics:")
print(df.describe())

🧾 Column Names in Your Dataset:
['State', 'Crop', 'Year', 'Area_Hectares', 'Production_Tonnes']

📊 Data Preview:
         State       Crop  Year  Area_Hectares  Production_Tonnes
0   Tamil Nadu       Rice  2020        1200000            3600000
1       Kerala     Banana  2020         450000            1600000
2       Punjab      Wheat  2020        1800000            5400000
3      Gujarat     Cotton  2020         700000            1800000
4  Maharashtra  Sugarcane  2020         900000            7200000

🔍 Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State              5 non-null      object
 1   Crop               5 non-null      object
 2   Year               5 non-null      int64
 3   Area_Hectares      5 non-null      int64
 4   Production_Tonnes  5 non-null      int64
dtypes: int64(3), object(2)
memory usage: 332.0+ bytes

📈 Summary Statistics:
         Year  Area_Hectares  Production_Tonnes
count     5.0   5.000000e+00       5.000000e+00
mean   2020.0   1.010000e+06       3.920000e+06
std       0.0   5.200961e+05       2.394160e+06
min    2020.0   4.500000e+05       1.600000e+06
25%    2020.0   7.000000e+05       1.800000e+06
50%    2020.0   9.000000e+05       3.600000e+06
75%    2020.0   1.200000e+06       5.400000e+06
max    2020.0   1.800000e+06       7.200000e+06

In [16]:
# OPTIONAL: Try to auto-detect correct column names (manually adjust if needed)
# Try to find columns similar to 'Rainfall' and 'Crop Yield'
rainfall_col = [col for col in df.columns if 'rain' in col.lower()][0]
yield_col = [col for col in df.columns if 'yield' in col.lower()][0]
crop_col = [col for col in df.columns if 'crop' in col.lower()][0]

print(f"\nUsing columns: Rainfall = {rainfall_col}, Yield = {yield_col}, Crop = {crop_col}")

# Plot
plt.figure(figsize=(8, 5))
sns.scatterplot(data=df, x=rainfall_col, y=yield_col, hue=crop_col)
plt.title('Crop Yield vs Rainfall')
plt.xlabel(rainfall_col)
plt.ylabel(yield_col)
plt.grid(True)
plt.tight_layout()
plt.show()

IndexError: list index out of range